#!/bin/bash

set -exu

export CLUSTER_NAME="${1:-webhook}"
export K3S_VERSION="${2:-v1.28.9-k3s1}"

k3d registry create gha -p 42765
k3d cluster create $CLUSTER_NAME --servers 1 --agents 1 \
    --registry-use gha:42765 \
    --image "rancher/k3s:${K3S_VERSION}" --api-port 6550

# waits until all nodes are ready
wait_for_nodes(){
  timeout=120
  start_time=$(date +%s)
  echo "wait until all agents are ready"
  while :
  do
    current_time=$(date +%s)
    elapsed_time=$((current_time - start_time))
    if [ $elapsed_time -ge $timeout ]; then
        echo "Timeout reached, exiting..."
        exit 1
    fi

    readyNodes=1
    statusList=$(kubectl get nodes --no-headers | awk '{ print $2}')
    # shellcheck disable=SC2162
    while read status
    do
      current_time=$(date +%s)
      elapsed_time=$((current_time - start_time))
      if [ $elapsed_time -ge $timeout ]; then
          echo "Timeout reached, exiting..."
          exit 1
      fi
      if [ "$status" == "NotReady" ] || [ "$status" == "" ]
      then
        readyNodes=0
        break
      fi
    done <<< "$(echo -e  "$statusList")"
    # all nodes are ready; exit
    if [[ $readyNodes == 1 ]]
    then
      break
    fi
    sleep 1
  done
}

wait_for_nodes

echo "k3d cluster $CLUSTER_NAME is ready"

kubectl cluster-info --context k3d-${CLUSTER_NAME}
kubectl config use-context k3d-${CLUSTER_NAME}
kubectl get nodes -o wide
kubectl get pods -A
