#!/bin/bash

set -exu

DIR1=$HOME/git/ericpromislow/rancher/webhook/.github/workflows/scripts

export CLUSTER_NAME="${1:-webhook}"
export K3S_VERSION=v1.28.9-k3s1
export RANCHER_IMAGE_TAG=v2.9-head
export VERSION=2.9
export ARCH=amd64
export CHART_PATH=$HOME/trash/rancher.tgz

# $DIR1/setup-cluster.sh

echo "Done setting up cluster"
read y

# k3d image import dist/rancher-webhook-image.tar -c webhook || true
echo "Done loading webhook image"
read y

# $DIR1/start-rancher.sh

echo "Done starting rancher"
read y

export IMAGE_REPO=rancher/webhook
source dist/tags
export HELM_CHART_VERSION="$HELM_CHART_VERSION"
export TAG="$TAG"
export HELM_TAG="$HELM_TAG"
source dist/image_tag
export IMAGE_TAG="${IMAGE_TAG}"
# export IMAGE_TAG=v0.5.0-rc.9.test.1-amd64

# source scripts/version


$DIR1/integration-test-ci
