#!/bin/bash

set -exu -o pipefail

# Sample cmd line:
# ARCH=amd64 REPO=morspin TAG=v2.10.3-dev-amd64.73 ~/git/ericpromislow/rancher/rancher-dev-tools/scripts/change-steve-k8s
# ARCH=arm64 REPO=morspin TAG=v2.10.3-dev-arm64.73 ~/git/ericpromislow/rancher/rancher-dev-tools/scripts/change-steve-k8s

# ARCH=amd64 REPO=morspin TAG=v2.10.3-dev-amd64.76 ~/git/ericpromislow/rancher/rancher-dev-tools/scripts/change-steve-k8s
# ARCH=arm64 REPO=morspin TAG=v2.10.3-dev-arm64.76 ~/git/ericpromislow/rancher/rancher-dev-tools/scripts/change-steve-k8s

# targetting 2.11 from code ...
# ARCH=amd64 REPO=morspin TAG=v2.11.2-dev-amd64.003 ~/git/ericpromislow/rancher/rancher-dev-tools/scripts/change-steve-k8s
# ARCH=arm64 REPO=morspin TAG=v2.12.2-dev-arm64.003 ~/git/ericpromislow/rancher/rancher-dev-tools/scripts/change-steve-k8s

export ARCH="${ARCH:-amd64}"
export CHART_REPO=morspin
export REPO=morspin
export COMMIT=$(git rev-parse --short HEAD)
export TAG="${TAG:-$(yq '.env.TAG | sub("-.*", "")' < .github/workflows/pull-request.yml)-${COMMIT}}"
export TARGET_ARCH="${TARGET_ARCH:-$ARCH}"
export TARGET_REPO=$REPO/rancher:$TAG

# Pull in values from `make quick'
RKE_VERSION=$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $2}')
if [[ -z "$RKE_VERSION" ]]; then
   RKE_VERSION=$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $4}')
fi
CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=$(yq '.provisioningCAPIVersion' < build.yaml)
CATTLE_RANCHER_WEBHOOK_VERSION=$(yq '.webhookVersion' < build.yaml)


if [ ! -e bin/agent-$ARCH ] ; then
    ./scripts/build-agent
    cp bin/agent-$ARCH package/agent
else
    cmp bin/agent-$ARCH package/agent || cp bin/agent-$ARCH package/agent
fi
TARGET_REPO=$TARGET_REPO REPO=$REPO IMAGE_TAG=$TAG ./dev-scripts/build-local.sh

docker push $REPO/rancher:$TAG

case $ARCH in
    amd64)
        export AGENT_ARCH="${AGENT_ARCH:-amd64}"
        ATAG=$(echo $TAG | sed 's/arm64/amd64/')
        docker buildx build \
    --build-arg VERSION="${TAG}" \
    --build-arg ARCH="${AGENT_ARCH}" \
    --build-arg RANCHER_TAG="${TAG}" \
    --build-arg RANCHER_REPO="${REPO}" \
    --build-arg COMMIT="${COMMIT}" \
    --build-arg RKE_VERSION="${RKE_VERSION}" \
    --build-arg CATTLE_RANCHER_WEBHOOK_VERSION="${CATTLE_RANCHER_WEBHOOK_VERSION}" \
    --build-arg CATTLE_RANCHER_PROVISIONING_CAPI_VERSION="${CATTLE_RANCHER_PROVISIONING_CAPI_VERSION}" \
    --tag "${REPO}"/rancher-agent:"${ATAG}" \
    --platform=linux/amd64 \
    --file package/Dockerfile-agent-dev ./package

        docker push $REPO/rancher-agent:$ATAG
        ;;
esac

# echo "Go run install-rancher"

echo install-rancher $1
