#!/bin/sh

echo '#!/bin/sh'
echo ''
echo 'set -e'
echo ''

cd ~/workspace/rancher
echo mkdir -p '~/workspace/rancher'
echo cd '~/workspace/rancher'
for x in * ; do
  if [ -e "$x/.git" ] ; then
    cd "$x"
    X="$(git remote -v | grep -e origin  -e fetch)"
    if [[ "$X" =~ github.com:rancher/ ]] ; then
      repo=$(echo $x | sed s@/@@)
      echo "git clone git@github.com:rancher/$repo.git"
      echo "cd $repo"
      echo "git pull"
      echo "cd .."
      echo ""
    fi
    cd ..
  fi
done

cd ~/git/ericpromislow/rancher
echo mkdir -p '~/git/ericpromislow/rancher'
echo cd '~/git/ericpromislow/rancher'
for x in * ; do
  if [ -e "$x/.git" ] ; then
    cd "$x"
    X="$(git remote -v | grep -e origin  -e fetch)"
    if [[ "$X" =~ rancher ]] ; then
      repo=$(echo $x | sed s@/@@)
      echo "git clone git@github.com:rancher/$repo.git"
      echo "cd $repo"
      echo "git pull"
      echo "fix-repo $repo"
      echo sync-from-upstream
      echo "cd .."
      echo ""
    fi
    cd ..
  fi
done

echo 'go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest'

echo '# get these progs:'
echo '# git'
echo '# vim'
echo '# ruby'
echo '# apt-get install build-essential curl'
echo '... homebrew get URL'
echo '# brew install golang'
echo '# brew install gh'
echo '# gh auth login'
