#!/usr/bin/env bash

set -ex

# These are idempotent - no failure if already installed

helm repo add cert-manager https://charts.jetstack.io
 
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

helm repo list | grep -q jetstack || helm repo add jetstack https://charts.jetstack.io

helm repo update

helm upgrade --install cert-manager --namespace cert-manager cert-manager/cert-manager --set installCRDs=true --set "extraArgs[0]=--enable-certificate-owner-ref=true" --create-namespace --timeout 10m --wait

kubectl rollout status --namespace cert-manager deploy/cert-manager --timeout 1m

VERSION=2.8
helm upgrade --install rancher rancher-latest/rancher --version $VERSION --namespace cattle-system --set hostname=localhost --wait --timeout=10m --create-namespace

# helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --set hostname=localhost --wait --timeout=10m --create-namespace --set rancherImageTag="v2.9-head" --devel

BOOTSTRAP_PASSWORD=$(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ "\n" }}' | tee /dev/tty)

# New Rancher Password:
# oHvwIirH9dN3Su2i - 2024-04-15 version 2.8
# 

# build notes:

# Why does this take so long?:
# go build -ldflags '-X main.GitCommit=757c069 -X main.Version=757c069-dirty -extldflags -static -s' -o bin/backup-restore-operator

