#!/bin/bash



flip() {
    echo $1
    exit 1
}

kubectl get ns | grep -s cattle && flip 'rancher already installed?'

set -exu

case "${1:-localhost}" in
localhost) ;;
*) pgrep -f 'ngrok http --inspect=false https://localhost:443' || flip 'ngrok not running' ;;
esac

NGROK=$1

helm repo list | grep -q cert-manager || helm repo add cert-manager https://charts.jetstack.io
helm repo list | grep -q rancher-latest || helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo list | grep -q rancher-alpha || helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha
helm repo list | grep -q jetstack || helm repo add jetstack https://charts.jetstack.io

helm repo update

helm upgrade --install cert-manager --namespace cert-manager cert-manager/cert-manager --set crds.enabled=true --set "extraArgs[0]=--enable-certificate-owner-ref=true" --create-namespace --wait --timeout=10m
 
kubectl rollout status --namespace cert-manager deploy/cert-manager --timeout 1m

# ngrok http --inspect=false https://localhost:443

case $NGROK in
    localhost) NGROK1=localhost ;;
    *) NGROK1="${NGROK}".ngrok.app ;;
esac

VERSION=2.9.0
CHART_PATH=rancher-latest/rancher

# Stuff for the agent-tls-mode problem
RANCHER_IMAGE=morspin/rancher
RANCHER_IMAGE_TAG=v10b

helm upgrade --install rancher "$CHART_PATH" --devel \
  --namespace cattle-system \
  --create-namespace \
  --set rancherImage="$RANCHER_IMAGE" \
  --set rancherImageTag="$RANCHER_IMAGE_TAG" \
  --set agentTLSMode=system-store \
  --version "${VERSION}" \
  --set tls=external \
  --set hostname="$NGROK1"

exit

VERSION=2.7.12
VERSION=2.8
CHART_PATH=rancher-latest/rancher

# Core rancher.....
#helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --set hostname="$NGROK1" --version $VERSION --wait --timeout=10m --create-namespace

# Stock rancher for this version

NGROK1=localhost
VERSION=2.8.2
# helm upgrade --install rancher rancher-latest/rancher --version $VERSION --namespace cattle-system --set hostname="$NGROK1" --wait --timeout=10m --create-namespace

# Regular canned install with auditlog:

#helm upgrade --install rancher rancher-latest/rancher --version $VERSION --namespace cattle-system --set hostname="$NGROK1" --wait --timeout=10m --create-namespace --set auditLog.level=1

# --set rancherImage="morspin/rancher" --set rancherImageTag="v02"

# --set auditLog.level=3


# helm upgrade --install rancher --namespace cattle-system --create-namespace --set rancherImage="morspin/rancher" --set rancherImageTag="v01" --set hostname=155e1595f943.ngrok.app

# helm upgrade --install rancher/rancher --namespace cattle-system --create-namespace --set hostname=155e1595f943.ngrok.app --set rancherImage="morspin/rancher" --set rancherImageTag="v01"
  
  
# /////////////////////////////////////////////////////////////////////////////
# To get audit-logging in:
# helm upgrade rancher rancher-latest/rancher --versihelm upgrade rancher rancher-latest/rancher --verison 2.8 --namespace cattle-system --set auditLog.level=1 --reuse-vaon 2.8 --namespace cattle-system --set auditLog.level=1 --reuse-values
