#!/bin/bash

flip() {
    echo $1
    exit 1
}

kubectl get ns | grep -s cattle && flip 'rancher already installed?'

pgrep -f 'ngrok http --inspect=false https://localhost:443' || flip 'ngrok not running'

set -exu

NGROK=$1

helm repo list | grep -q cert-manager || helm repo add cert-manager https://charts.jetstack.io
helm repo list | grep -q rancher-latest || helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo list | grep -q jetstack || helm repo add jetstack https://charts.jetstack.io

helm repo update

helm upgrade --install cert-manager --namespace cert-manager cert-manager/cert-manager --set installCRDs=true --set "extraArgs[0]=--enable-certificate-owner-ref=true" --create-namespace --wait --timeout=10m
 
# kubectl get pods --namespace cert-manager
kubectl rollout status --namespace cert-manager deploy/cert-manager --timeout 1m

# ngrok http --inspect=false https://localhost:443


NGROK1="${NGROK}".ngrok.app
# NGROK1=localhost

VERSION=2.8
VERSIONTAG=v03
#helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --set hostname="$NGROK1" --wait --timeout=10m --create-namespace --set rancherImage="morspin/rancher" --set rancherImageTag="$VERSIONTAG"

# Core rancher.....
#helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --set hostname="$NGROK1" --wait --timeout=10m --create-namespace --set rancherImage="rancher/rancher" --set rancherImageTag="v2.9-head"

# For later???
helm upgrade --install rancher rancher-latest/rancher --version $VERSION --namespace cattle-system --set hostname="$NGROK1" --wait --timeout=10m --create-namespace
# --set rancherImage="morspin/rancher" --set rancherImageTag="v02"

# --set auditLog.level=3


# helm upgrade --install rancher --namespace cattle-system --create-namespace --set rancherImage="morspin/rancher" --set rancherImageTag="v01" --set hostname=155e1595f943.ngrok.app

# helm upgrade --install rancher/rancher --namespace cattle-system --create-namespace --set hostname=155e1595f943.ngrok.app --set rancherImage="morspin/rancher" --set rancherImageTag="v01"
  
  
